# Generated by Django 4.2.29 on 2026-04-08 07:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='wetland',
            new_name='mapping_wet_status_d2b6e3_idx',
            old_name='mapping_wet_status_idx',
        ),
        migrations.RenameIndex(
            model_name='wetland',
            new_name='mapping_wet_risk_le_19f7ef_idx',
            old_name='mapping_wet_risk_idx',
        ),
        migrations.RenameIndex(
            model_name='wetland',
            new_name='mapping_wet_village_050546_idx',
            old_name='mapping_wet_village_idx',
        ),
        migrations.RenameIndex(
            model_name='wetland',
            new_name='mapping_wet_date_di_afecd7_idx',
            old_name='mapping_wet_date_idx',
        ),
        migrations.RenameIndex(
            model_name='wetlandmonitoringrecord',
            new_name='mapping_wet_wetland_81394e_idx',
            old_name='mapping_mon_wetland_year_idx',
        ),
        migrations.RenameIndex(
            model_name='wetlandmonitoringrecord',
            new_name='mapping_wet_risk_cl_40e355_idx',
            old_name='mapping_mon_risk_idx',
        ),
        migrations.RemoveField(
            model_name='wetlandmonitoringrecord',
            name='slope_std',
        ),
        migrations.AlterField(
            model_name='wetlandmonitoringrecord',
            name='erosion_risk',
            field=models.FloatField(blank=True, help_text='Erosion risk index (0=Low, 1=Moderate, 2=High)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
        ),
    ]
