# Generated by Django 4.2.29 on 2026-04-11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0002_rename_mapping_wet_status_idx_mapping_wet_status_d2b6e3_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelapseJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2013)])),
                ('end_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2013)])),
                ('buffer_meters', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0)])),
                ('cloud_threshold', models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('frames_per_second', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('dimensions', models.IntegerField(default=300, validators=[django.core.validators.MinValueValidator(64), django.core.validators.MaxValueValidator(1024)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('progress_percent', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('error_message', models.TextField(blank=True)),
                ('frame_urls', models.JSONField(blank=True, default=list)),
                ('gif_relative_path', models.CharField(blank=True, max_length=500)),
                ('gif_source_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('wetland', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timelapse_jobs', to='mapping.wetland')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='mapping_tim_status_3c3f48_idx'), models.Index(fields=['created_at'], name='mapping_tim_created_3c033d_idx'), models.Index(fields=['wetland', 'created_at'], name='mapping_tim_wetland_8fef4b_idx')],
            },
        ),
    ]
