# Generated by Django 4.2.29 on 2026-04-29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0003_timelapsejob'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation', models.CharField(choices=[('grazing', 'Grazing'), ('erosion', 'Erosion'), ('invasive_species', 'Invasive species')], max_length=32)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('info', 'Info'), ('resolved', 'Resolved')], max_length=20)),
                ('comments', models.TextField()),
                ('submitted_by', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wetland', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_inputs', to='mapping.wetland')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['wetland', 'created_at'], name='mapping_com_wetland_5f186b_idx'), models.Index(fields=['severity'], name='mapping_com_severit_272390_idx')],
            },
        ),
    ]
